version: '3.8'

services:
  web:
    image: ${DOCKER_REGISTRY}/${DOCKER_REPOSITORY}/${DOCKER_IMAGE_NAME}:latest
    container_name: ${ENV_PROJECT_NAME}
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "${DOCKER_PORT}:8008"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge